name: git commit

on:
  push:
    branch:
      - git-action-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: bash
      run: |
        git branch -a
        git switch -c test-$(date "+%Y%m%d%H%M%S") master
        #git config --global user.email "suetsugu.r@gmail.com"
        #git config --global user.name "suer"
        #git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        #git config --global user.name "github-actions[bot]"
        git commit --allow-empty -m "commit"
        git push origin HEAD
      env:
#        GIT_AUTHOR_NAME: suer[bot]
#        GIT_AUTHOR_EMAIL: suetsugu.r@gmail.com
#        GIT_COMMITTER_NAME: suer[bot]
#        GIT_COMMITTER_EMAIL: suetsugu.r@gmail.com
        GIT_AUTHOR_NAME: suer[bot]
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: suer[bot]
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

