name: test

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: setup vars
        id: setup-vars
        run: |
          TODAY=$(date +"%Y-%m-%d")
          echo "foo=${TODAY}" >> $GITHUB_OUTPUT
      - name: echo vars
        run: |
          echo ${{ steps.setup-vars.outputs.foo }}

